#!/usr/bin/env node
/*
 * generate.mjs - rebuilds freight-alert.user.js from live Shopify data.
 *
 * Queries every product tagged "freight", "freefreight", or "liftgate",
 * bakes their SKUs + product IDs into the userscript, and (only when that
 * set actually changed) bumps the @version so Tampermonkey auto-updates
 * every installed copy.
 *
 * Env vars:
 *   SHOPIFY_STORE        myshopify subdomain      (default: hollywood-djmi)
 *   SHOPIFY_ADMIN_TOKEN  Admin API access token   (REQUIRED - read_products)
 *   GITHUB_REPOSITORY    owner/repo               (set automatically in Actions)
 *   GITHUB_REF_NAME      branch name              (set automatically in Actions)
 *
 * Run locally:  SHOPIFY_ADMIN_TOKEN=shpat_xxx node generate.mjs
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';

const STORE = process.env.SHOPIFY_STORE || 'hollywood-djmi';
const TOKEN = process.env.SHOPIFY_ADMIN_TOKEN;
const API_VERSION = '2025-01';
const TAG_QUERY = 'tag:freight OR tag:freefreight OR tag:liftgate';
const OUT_FILE = 'freight-alert.user.js';

// Auto-update URLs (self-configuring from the repo it runs in).
const REPO = process.env.GITHUB_REPOSITORY || 'YOUR_GITHUB_USER/hdj-freight-alert';
const BRANCH = process.env.GITHUB_REF_NAME || 'main';
const RAW_URL = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/${OUT_FILE}`;

const ENDPOINT = `https://${STORE}.myshopify.com/admin/api/${API_VERSION}/graphql.json`;

export function hashData({ ids, skus }) {
  return createHash('sha256')
    .update(JSON.stringify({ ids, skus }))
    .digest('hex')
    .slice(0, 12);
}

async function gql(query, variables) {
  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Shopify-Access-Token': TOKEN },
    body: JSON.stringify({ query, variables }),
  });
  if (!res.ok) throw new Error(`Shopify HTTP ${res.status}: ${await res.text()}`);
  const json = await res.json();
  if (json.errors) throw new Error('Shopify GraphQL error: ' + JSON.stringify(json.errors));
  return json.data;
}

async function fetchFreight() {
  const ids = new Set();
  const skus = new Set();
  let after = null;
  let page = 0;
  const PAGE_QUERY = `
    query($after: String) {
      products(first: 100, query: ${JSON.stringify(TAG_QUERY)}, after: $after) {
        edges { node { legacyResourceId variants(first: 50) { edges { node { sku } } } } }
        pageInfo { hasNextPage endCursor }
      }
    }`;
  do {
    const data = await gql(PAGE_QUERY, { after });
    const conn = data.products;
    for (const { node } of conn.edges) {
      ids.add(node.legacyResourceId);
      for (const v of node.variants.edges) {
        const s = (v.node.sku || '').trim();
        if (s) skus.add(s.toUpperCase());
      }
    }
    after = conn.pageInfo.hasNextPage ? conn.pageInfo.endCursor : null;
    page++;
    console.log(`  page ${page}: ${conn.edges.length} products (running total ${ids.size})`);
  } while (after);

  return {
    ids: [...ids].sort(),
    skus: [...skus].sort(),
  };
}

export function buildScript({ ids, skus }, version, dataHash) {
  const idLines = ids.map((i) => `  "${i}",`).join('\n');
  const skuLines = skus.map((s) => `  "${s}",`).join('\n');
  return `// ==UserScript==
// @name         Hollywood DJ - Freight Item Alert (Draft Orders)
// @namespace    hollywooddj.freight
// @version      ${version}
// @description  Warns the sales team when a draft order / order contains an item that ships FREIGHT (LTL). Auto-updates.
// @author       Hollywood DJ
// @match        https://admin.shopify.com/store/*/draft_orders*
// @match        https://admin.shopify.com/store/*/orders*
// @downloadURL  ${RAW_URL}
// @updateURL    ${RAW_URL}
// @run-at       document-idle
// @grant        none
// ==/UserScript==

/*
 * Auto-generated by generate.mjs from live Shopify data.
 * Freight list = every product tagged "freight", "freefreight", OR "liftgate".
 * DO NOT hand-edit; changes are overwritten on the next scheduled build.
 * DATA-HASH: ${dataHash}
 */

(function () {
  'use strict';

  // --- Baked freight catalog (SKUs) -------------------------------------------
  const FREIGHT_SKUS = new Set([
${skuLines}
  ]);

  // --- Baked freight catalog (product IDs) ------------------------------------
  const FREIGHT_IDS = new Set([
${idLines}
  ]);

  const BANNER_ID = 'hdj-freight-banner';
  const PILL_CLASS = 'hdj-freight-pill';
  const ROW_CLASS = 'hdj-freight-row';
  const SKU_RE = /H-[A-Z0-9]+(?:-[A-Z0-9]+)+/gi;

  function injectStyle() {
    if (document.getElementById('hdj-freight-style')) return;
    const s = document.createElement('style');
    s.id = 'hdj-freight-style';
    s.textContent = \`
      #\${BANNER_ID}{position:sticky;top:0;z-index:2147483000;
        background:#b3261e;color:#fff;font:600 14px/1.4 -apple-system,Segoe UI,Roboto,sans-serif;
        padding:12px 16px;box-shadow:0 2px 6px rgba(0,0,0,.25);display:flex;gap:10px;align-items:flex-start}
      #\${BANNER_ID} .hdj-x{margin-left:auto;cursor:pointer;font-weight:700;opacity:.85;padding:0 4px}
      #\${BANNER_ID} .hdj-x:hover{opacity:1}
      #\${BANNER_ID} ul{margin:4px 0 0;padding-left:18px;font-weight:500}
      .\${ROW_CLASS}{outline:2px solid #b3261e !important;outline-offset:-2px;border-radius:4px}
      .\${PILL_CLASS}{display:inline-block;margin-left:6px;padding:1px 7px;border-radius:10px;
        background:#b3261e;color:#fff;font:700 10px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;
        letter-spacing:.4px;vertical-align:middle}
    \`;
    document.head.appendChild(s);
  }

  function onOrderPage() {
    const p = location.pathname;
    return /\\/draft_orders(\\/|$)/.test(p) || /\\/orders(\\/|$)/.test(p);
  }

  function findFreight() {
    const hits = new Map();
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null);
    let n;
    while ((n = walker.nextNode())) {
      const t = n.nodeValue;
      if (!t || t.indexOf('H-') === -1) continue;
      const found = t.match(SKU_RE);
      if (!found) continue;
      for (const raw of found) {
        const sku = raw.toUpperCase();
        if (FREIGHT_SKUS.has(sku) && !hits.has(sku)) {
          hits.set(sku, { sku, el: rowFor(n.parentElement), label: labelFor(n.parentElement, sku) });
        }
      }
    }
    document.querySelectorAll('a[href*="/products/"]').forEach((a) => {
      const m = a.getAttribute('href').match(/\\/products\\/(\\d+)/);
      if (m && FREIGHT_IDS.has(m[1])) {
        const key = 'PID:' + m[1];
        if (!hits.has(key)) hits.set(key, { sku: null, el: rowFor(a), label: (a.textContent || '').trim() || ('product ' + m[1]) });
      }
    });
    return [...hits.values()];
  }

  function rowFor(el) {
    let cur = el, best = el;
    for (let i = 0; i < 12 && cur && cur !== document.body; i++) {
      const r = cur.getBoundingClientRect ? cur.getBoundingClientRect() : null;
      if (r && r.height > 28 && r.height < 220 && r.width > 260) best = cur;
      if (cur.matches && cur.matches('tr, li, [role="row"]')) return cur;
      cur = cur.parentElement;
    }
    return best;
  }

  function labelFor(el, sku) {
    const row = rowFor(el);
    let txt = (row && row.textContent || '').replace(/\\s+/g, ' ').trim();
    if (txt.length > 90) txt = txt.slice(0, 90) + '\\u2026';
    return txt || sku;
  }

  function decorateRows(hitList) {
    hitList.forEach((h) => {
      if (!h.el || !h.el.nodeType) return;
      if (!h.el.classList.contains(ROW_CLASS)) h.el.classList.add(ROW_CLASS);
      if (!h.el.querySelector('.' + PILL_CLASS)) {
        const pill = document.createElement('span');
        pill.className = PILL_CLASS;
        pill.textContent = 'FREIGHT / LTL';
        (h.el.querySelector('a,span,div') || h.el).appendChild(pill);
      }
    });
  }

  function renderBanner(hitList) {
    let banner = document.getElementById(BANNER_ID);
    if (!hitList.length) { if (banner) banner.remove(); clearRows(); return; }
    const listItems = hitList.map((h) => '<li>' + esc(h.label) + '</li>').join('');
    const n = hitList.length;
    const html =
      '<div style="font-size:20px;line-height:1">\\u26A0</div>' +
      '<div><div>THIS ORDER INCLUDES ' + n + ' FREIGHT ITEM' + (n > 1 ? 'S' : '') +
      ' - ships LTL freight. Confirm freight/liftgate cost &amp; delivery before quoting.</div>' +
      '<ul>' + listItems + '</ul></div>' +
      '<div class="hdj-x" title="Hide">\\u2715</div>';
    if (!banner) {
      banner = document.createElement('div');
      banner.id = BANNER_ID;
      const host = document.querySelector('main') || document.body;
      host.insertBefore(banner, host.firstChild);
    }
    if (banner.__html !== html) { banner.innerHTML = html; banner.__html = html; }
    banner.querySelector('.hdj-x').onclick = () => banner.remove();
  }

  function clearRows() {
    document.querySelectorAll('.' + ROW_CLASS).forEach((e) => e.classList.remove(ROW_CLASS));
    document.querySelectorAll('.' + PILL_CLASS).forEach((e) => e.remove());
  }

  function esc(s) { return (s || '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }

  let scheduled = false;
  function scan() {
    scheduled = false;
    if (!onOrderPage()) { const b = document.getElementById(BANNER_ID); if (b) b.remove(); clearRows(); return; }
    injectStyle();
    clearRows();
    const hits = findFreight();
    decorateRows(hits);
    renderBanner(hits);
  }
  function schedule() { if (!scheduled) { scheduled = true; setTimeout(scan, 250); } }

  new MutationObserver(schedule).observe(document.documentElement, { childList: true, subtree: true });
  setInterval(schedule, 1500);
  schedule();
})();
`;
}

// --- main --------------------------------------------------------------------
async function main() {
  if (!TOKEN) {
    console.error('ERROR: SHOPIFY_ADMIN_TOKEN is not set.');
    process.exit(1);
  }
  console.log(`Fetching freight products from ${STORE}.myshopify.com ...`);
  const data = await fetchFreight();
  console.log(`Total: ${data.ids.length} products, ${data.skus.length} SKUs.`);

  const dataHash = hashData(data);

  // Decide version: keep it identical if the data is unchanged, else bump the
  // last segment so Tampermonkey sees a newer version.
  let version = '1.2.0';
  let changed = true;
  if (existsSync(OUT_FILE)) {
    const prev = readFileSync(OUT_FILE, 'utf8');
    const prevHash = (prev.match(/DATA-HASH:\s*([0-9a-f]+)/) || [])[1];
    const prevVer = (prev.match(/@version\s+([0-9.]+)/) || [])[1] || '1.2.0';
    if (prevHash === dataHash) {
      console.log('No change in freight list - nothing to do.');
      changed = false;
      version = prevVer;
    } else {
      const seg = prevVer.split('.');
      seg[seg.length - 1] = String((parseInt(seg[seg.length - 1], 10) || 0) + 1);
      version = seg.join('.');
      console.log(`Freight list changed - bumping ${prevVer} -> ${version}.`);
    }
  }

  if (changed) {
    writeFileSync(OUT_FILE, buildScript(data, version, dataHash), 'utf8');
    console.log(`Wrote ${OUT_FILE} (v${version}). Auto-update URL: ${RAW_URL}`);
  } else {
    console.log('Output left unchanged.');
  }
}

// Run only when executed directly (not when imported by the initial builder).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
